/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.DatesList;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Date;

@Validated
@Api(value = "dateslist", description = "the dateslist API")
@RequestMapping(value = "")
public interface DatesListApi {

    @ApiOperation(value = "Uzyskaj dostępne terminy", nickname = "getdates", notes = "", response = DatesList.class, tags={ "Rejestracja", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Terminy udostępnione prawidłowo", response = Date.class),
        @ApiResponse(code = 500, message = "Brak możliwości udostępnienia terminów w chwili obecnej") })
    @RequestMapping(value = "/dateslist",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<DatesList> getDates(@RequestHeader String Authorization);


    @ApiOperation(value = "Zarezerwuj termin", nickname = "postdates", notes = "", response = Date.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Rejestracja", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Termin zarezerwowany prawidlowo", response = Date.class),
        @ApiResponse(code = 500, message = "Wystapil blad w trakcie rezerwacji, spróbuj ponownie") })
    @RequestMapping(value = "/dateslist",
        produces = { "text/plain" },
        consumes = { "text/plain" },
        method = RequestMethod.POST)
    ResponseEntity<String> postDates(@ApiParam(value = "Data do zarezerwowania"  )  @RequestBody String date, @RequestHeader String Authorization,@RequestHeader("X-HMAC-SIGNATURE") String HeaderHMAC) throws NoSuchAlgorithmException, InvalidKeyException;

}
