/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.LabResults;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


@Validated
@Api(value = "labresults", description = "the labresults API")
@RequestMapping(value = "")
public interface LabResultsApi {

    @ApiOperation(value = "Uzyskaj rezultaty badan", nickname = "getlabresults", notes = "", response = LabResults.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Wyniki badań", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Przedstawiono wyniki badań", response = LabResults.class),
        @ApiResponse(code = 400, message = "niepoprawnie podany użytkownik"),
        @ApiResponse(code = 500, message = "Brak możliwości udostępnienia wyników w chwili obecnej") })
    @RequestMapping(value = "/labresults/{username}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity getLabResults(@ApiParam(value = "username",required=true) @PathVariable("username") String username, @RequestHeader String Authorization);

}
